export const cookbookImages = [
//   { id: 1, src: "/img/cookbook/1.jpg" },
  { id: 2, src: "/img/cookbook/2.jpg" },
  { id: 3, src: "/img/cookbook/3.jpg" },
  { id: 4, src: "/img/cookbook/4.jpg" },
  { id: 5, src: "/img/cookbook/5.jpg" },
  { id: 6, src: "/img/cookbook/6.jpg" },
  { id: 7, src: "/img/cookbook/7.jpg" },
  { id: 8, src: "/img/cookbook/8.jpg" },
//   { id: 9, src: "/img/cookbook/9.jpg" },
//   { id: 10, src: "/img/cookbook/10.jpg" },
//   { id: 11, src: "/img/cookbook/11.jpg" },
  { id: 12, src: "/img/cookbook/12.jpg" },
  { id: 13, src: "/img/cookbook/13.jpg" },
  { id: 14, src: "/img/cookbook/14.jpg" },
  { id: 15, src: "/img/cookbook/15.jpg" },
//   { id: 16, src: "/img/cookbook/16.jpg" },
  { id: 17, src: "/img/cookbook/17.jpg" },
  { id: 18, src: "/img/cookbook/18.jpg" },
  { id: 19, src: "/img/cookbook/19.jpg" },
  { id: 20, src: "/img/cookbook/20.jpg" },
  { id: 21, src: "/img/cookbook/21.jpg" },
  { id: 22, src: "/img/cookbook/22.jpg" },
  { id: 23, src: "/img/cookbook/23.jpg" },
];

export const allCookbookImages = [
  { id: 1, src: "/img/cookbook/1.jpg" },
  { id: 2, src: "/img/cookbook/2.jpg" },
  { id: 3, src: "/img/cookbook/3.jpg" },
  { id: 4, src: "/img/cookbook/4.jpg" },
  { id: 5, src: "/img/cookbook/5.jpg" },
  { id: 6, src: "/img/cookbook/6.jpg" },
  { id: 7, src: "/img/cookbook/7.jpg" },
  { id: 8, src: "/img/cookbook/8.jpg" },
  { id: 9, src: "/img/cookbook/9.jpg" },
  { id: 10, src: "/img/cookbook/10.jpg" },
  { id: 11, src: "/img/cookbook/11.jpg" },
  { id: 12, src: "/img/cookbook/12.jpg" },
  { id: 13, src: "/img/cookbook/13.jpg" },
  { id: 14, src: "/img/cookbook/14.jpg" },
  { id: 15, src: "/img/cookbook/15.jpg" },
  { id: 16, src: "/img/cookbook/16.jpg" },
  { id: 17, src: "/img/cookbook/17.jpg" },
  { id: 18, src: "/img/cookbook/18.jpg" },
  { id: 19, src: "/img/cookbook/19.jpg" },
  { id: 20, src: "/img/cookbook/20.jpg" },
  { id: 21, src: "/img/cookbook/21.jpg" },
  { id: 22, src: "/img/cookbook/22.jpg" },
  { id: 23, src: "/img/cookbook/23.jpg" },
];
