export const cookbookImages = [
  //   { src: "/img/cookbook/1.jpg" },
  { src: "/img/cookbook/2.jpg" },
  { src: "/img/cookbook/3.jpg" },
  { src: "/img/cookbook/4.jpg" },
  { src: "/img/cookbook/5.jpg" },
  { src: "/img/cookbook/6.jpg" },
  { src: "/img/cookbook/7.jpg" },
  { src: "/img/cookbook/8.jpg" },
  //   { src: "/img/cookbook/9.jpg" },
  //   { src: "/img/cookbook/10.jpg" },
  //   { src: "/img/cookbook/11.jpg" },
  { src: "/img/cookbook/12.jpg" },
  { src: "/img/cookbook/13.jpg" },
  { src: "/img/cookbook/14.jpg" },
];

export const allCookbookImages = [
  { src: "/img/cookbook/1.jpg" },
  { src: "/img/cookbook/2.jpg" },
  { src: "/img/cookbook/3.jpg" },
  { src: "/img/cookbook/4.jpg" },
  { src: "/img/cookbook/5.jpg" },
  { src: "/img/cookbook/6.jpg" },
  { src: "/img/cookbook/7.jpg" },
  { src: "/img/cookbook/8.jpg" },
  { src: "/img/cookbook/9.jpg" },
  { src: "/img/cookbook/10.jpg" },
  { src: "/img/cookbook/11.jpg" },
  { src: "/img/cookbook/12.jpg" },
  { src: "/img/cookbook/13.jpg" },
  { src: "/img/cookbook/14.jpg" },
];
